language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer install
  - php bin/client.php setup:phantom --destination ./bin/

script: vendor/bin/phpunit --coverage-text --bootstrap tests/bootstrap.php tests
